apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cfg
  namespace: allen
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  10000;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      #gzip  on;

      include /etc/nginx/conf.d/*.conf;
    }
  server.conf: |
    upstream demo {
      server springboot-demo;
    }


    client_max_body_size 5000m;

    # When buffering is disabled, the request body is sent to proxied server immediately as ii is received
    proxy_request_buffering off;

    server {
      listen 80 default_server;

      location / {
        proxy_pass http://demo;

        proxy_connect_timeout       3600;
        proxy_send_timeout          3600;
        proxy_read_timeout          3600;
        send_timeout                3600;
      }
    }