apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: allen
spec:
  selector:
    app: nginx
  ports:
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  externalIPs:
    - 192.168.174.8